services:
  db1:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_PASSWORD: a1b2c3d4
      POSTGRES_USER: devdb
    ports:
      - '54321:5432'
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    networks:
      - red-backend-app

  pais-service:
    image: 'alvarosalazar/servicio-pais:0.1.9'
    ports:
      - '8081:8080'
    depends_on:
      - db1
    environment:
      DB_URL: jdbc:postgresql://db1/curso_springboot
      DB_USERNAME: devdb
      DB_PASSWORD: a1b2c3d4
      KEYCLOAK_URL: http://keycloak:8080
    networks:
      - red-backend-app

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    entrypoint: ["/opt/keycloak/bin/kc.sh"]
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db2/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    depends_on:
      - db2
    networks:
      - red-backend-app

  db2:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '54322:5432'
    networks:
      - red-backend-app

networks:
  red-backend-app:
    driver: bridge

volumes:
  postgres_data1:
    driver: local
  postgres_data2:
    driver: local